POST http://localhost:3001/spaces/ HTTP/1.1
content-type: application/json

{
    "name": "Pista de Tenis",
    "address": "Polideportivo La Alcayna",
    "capacity": "4"
}

// CTRL + ALT + R to send the request