POST http://localhost:3001/users/ HTTP/1.1
content-type: application/json

{
    "name": "kdaoijoijsadoidsaojidadoijasdjoias",
    "lastName": "Maquilon Perez",
    "email": "iliaqui.pe2@gmail.com",
    "password": "test",
    "birthdate": "2001-05-23",
    "address": "Plaza Escultor Jose Planes",
    "phone": "666666666",
    "isAdmin": "true"
}

// CTRL + ALT + R to send the request	