POST http://localhost:3001/users/ HTTP/1.1
content-type: application/json

{
    "username": "alriherAdmin",
    "name": "AlvaroAdmin",
    "lastName": "Admin",
    "email": "alvarorikelme25admin@gmail.com",
    "password": "123456789.Al",
    "birthdate": "2002-07-31",
    "address": "Calle Rio Ibor, 37",
    "phone": "633650556",
    "isAdmin": "true"
}

// CTRL + ALT + R to send the request	