PUT http://localhost:3001/users/3 HTTP/1.1
Content-Type: application/json

{
    "name": "Ilia",
    "lastName": "Maquilon Perez",
    "email": "iliaqui.pe@gmail.com",
    "password": "test",
    "birthdate": "2001-05-23",
    "address": "Plaza Escultor Jose Planes",
    "phone": "777777777",
    "isAdmin": "true"}

